version: '3.4'

services:
  azure-uploader:
    build: .
    environment:
      - CONTAINER_NAME=your-container-name
      - DESTINATION_DIRECTORY=/videos
      - STORAGE_ACCOUNT_NAME=your-storage-account-name
      - STORAGE_ACCOUNT_KEY=your-storage-account-key
    volumes:
      - /path/to/local/folder:/sharedvolume
    command: "keyword-of-the-filename"
