services:
  azure-uploader:
    build:
      context: .
      target: final
      args:
        - UID=1001
      cache_from:
        - ghcr.io/recorder-moe/azure-uploader:cache
      cache_to:
        - type=inline
    environment:
      - CONTAINER_NAME=your-container-name
      - DESTINATION_DIRECTORY=/videos
      - STORAGE_ACCOUNT_NAME=your-storage-account-name
      - STORAGE_ACCOUNT_KEY=your-storage-account-key
      - REMOVE_SUCCESS_FILES=false
    volumes:
      - /path/to/local/folder:/sharedvolume
    command: "keyword-of-the-filename"
